### ISSUE TITLE
Signature Search button doesnt work

### ISSUE THREAD

**Issue by vstathias** [schurerlab/LINCSDataPortal_2.0#10]
It doesnt redirect me to anything. 
-  tried Chrome Browser + Safari browser

**Comment by akoleti** [comment]
Noticed that. On it now

**Comment by akoleti** [comment]
Fixed now. Please check and close the issue

**Comment by djc183** [comment]
Link works and up/down gene boxes show up, but searching for genes doesn't give results, just perpetual loading screen.
