### ISSUE TITLE
Suggest terms disappear when they should not

### ISSUE THREAD

**Issue by dusicav** [schurerlab/LINCSDataPortal_2.0#15]
Start typing in the search box 'AC'.
Suggest terms under Perturbations 'Small Molecule' come up, bunch of them starting with AC, like AC1NWAOC, AC1LBR3D, AC1NWAKU, AC1OF35N, AC1LA7UC, AC1NSZMI, etc.
However, after '1' is added in the search box to make it 'AC1', all of the search terms disappear except '9-Fluoro-11,17,21-trihydroxy-16-methylpregna-1,4-diene-3,20-dione.

**Comment by akoleti** [comment]
This should be resolved now.
