### ISSUE TITLE
Incorrect plurality form of words

### ISSUE THREAD

**Issue by djc183** [schurerlab/LINCSDataPortal_2.0#19]
Assay summary page lists "Centers" even when there's only a single center listed for the assay.

![image](https://user-images.githubusercontent.com/24969261/64731055-6ecf7b00-d4ae-11e9-82c8-ef3292c269ba.png)

**Comment by akoleti** [comment]
Done

**Comment by djc183** [comment]
It needs to be dynamic.  Some of them do need to be plural, but if it's only 1, then no.

![image](https://user-images.githubusercontent.com/24969261/64878628-ef62b880-d621-11e9-9a3c-ed1fd103debb.png)

**Comment by akoleti** [comment]
hmm. Good one. I Can add 's as needed. Do you see that for any other fields

**Comment by djc183** [comment]
It should be done for all metadata, participants, and data fields, ideally.  Process/Processes needs it for sure.

**Comment by djc183** [comment]
"Model Systems" in upper right menu.

![image](https://user-images.githubusercontent.com/24969261/64970661-43fd7200-d874-11e9-850b-a9e210d8125e.png)

**Comment by djc183** [comment]
'UP' vs. "Down" in Signature Search page:

![image](https://user-images.githubusercontent.com/24969261/64971185-4b714b00-d875-11e9-98b5-5ac5b5079499.png)

**Comment by akoleti** [comment]
This should be fixed.
