### ISSUE TITLE
At home page, clicking on shRNAs and sgRNAs directs you to small molecules

### ISSUE THREAD

**Issue by vstathias** [schurerlab/LINCSDataPortal_2.0#25]

**Comment by djc183** [comment]
The same thing happens for signatures - clicking any signature type results in loading up ALL signatures.

![image](https://user-images.githubusercontent.com/24969261/64871407-34cbb980-d613-11e9-850e-c09b8a11df76.png)
Click protein binding
![image](https://user-images.githubusercontent.com/24969261/64871439-4319d580-d613-11e9-8b1b-2d9317bbd81a.png)
Get this

**Comment by akoleti** [comment]
Signatures is fixed now. I will look into SgRNA and shRNA

**Comment by akoleti** [comment]
#84
