### ISSUE TITLE
Limited showing from top-right icons

### ISSUE THREAD

**Issue by djc183** [schurerlab/LINCSDataPortal_2.0#31]
Clicking the pertubation icon in the top-right corner only shows 100 results, and they're all small molecules.  No sg- or shRNAs.

![image](https://user-images.githubusercontent.com/24969261/64863657-63419880-d603-11e9-9930-60474fb5b290.png)

**Comment by djc183** [comment]
UPDATE - this happens following clicking from the homepage search results/menu, as well.

**Comment by akoleti** [comment]
This should be fixed now.
