### ISSUE TITLE
Stretched images of small molecules on landing pages

### ISSUE THREAD

**Issue by djc183** [schurerlab/LINCSDataPortal_2.0#32]
On accessing a molecule's landing page, the structure image appears substantially stretched, though the text all appears fine.

![image](https://user-images.githubusercontent.com/24969261/64863831-bfa4b800-d603-11e9-9355-6430d87d15ed.png)
![image](https://user-images.githubusercontent.com/24969261/64863845-c6cbc600-d603-11e9-9840-95490a04b416.png)
![image](https://user-images.githubusercontent.com/24969261/64863859-cfbc9780-d603-11e9-995e-f8e503b7b695.png)

**Comment by akoleti** [comment]
should be fixed now.
