### ISSUE TITLE
Structure search page not loading

### ISSUE THREAD

**Issue by djc183** [schurerlab/LINCSDataPortal_2.0#33]
When clicking structure search, only a blank page comes up; no search/structure drawing box/etc.  Seen on Chrome.

![image](https://user-images.githubusercontent.com/24969261/64871225-cd156e80-d612-11e9-942e-094f9f5d79a0.png)

**Comment by chung88** [comment]
![image](https://user-images.githubusercontent.com/3586358/64968112-9daf6d80-d86f-11e9-9144-eff82f932f29.png)
