### ISSUE TITLE
Signature browse/page number buttons do nothing

### ISSUE THREAD

**Issue by djc183** [schurerlab/LINCSDataPortal_2.0#37]
Clicking on any of the numerical or prev/next buttons in the signature browse page simply refreshes the page, rather than actually moving through them.

![image](https://user-images.githubusercontent.com/24969261/64882893-0d351b00-d62c-11e9-81e9-dc25c8b2d93d.png)

**Comment by akoleti** [comment]
hmm. It is working for me. Let me try to reproduce

**Comment by djc183** [comment]
It looks like they're working, but there's no indication of what page is currently open, nor does the list go beyond 8.  I.e. if I'm on page 8 and click next, the bottom still says 1-8...
