### ISSUE TITLE
Signature search does not give results

### ISSUE THREAD

**Issue by djc183** [schurerlab/LINCSDataPortal_2.0#43]
Link works and up/down gene boxes show up, but searching for genes doesn't give results, just perpetual loading screen.
![image](https://user-images.githubusercontent.com/24969261/64972642-9f7d2f00-d877-11e9-81b9-f1163f4d4062.png)

**Comment by akoleti** [comment]
may be they don't have a match.

**Comment by akoleti** [comment]
try this: "genesUp":["ESR1","GREB1","LRRC6","GPR143","CCDC170","SCUBE2","ABAT","ST6GALNAC2","CACNA2D2","RHOH","TFF3","IQSEC1","CLSTN2","REPS2","CACNA1H","MRFAP1L1","ATP7B","CA5B","ARMT1","PRLR","CACNG4","XBP1","CRYL1","SLC9A2","ANXA9","ZMAT4","KIAA1324","KIAA1467","SULT2B1","BCAS1","MED13L","SEPT8","ADD1","ZFYVE21","BCAS3","CYFIP2","CHRD","COX6C","TOB1","MREG","SIAH2","GHR","GATA3","KDM2A","COLQ","HTT","SCGN","CA12","KIF16B","PVALB","SOX2","SIRT4","CBFA2T3","BEX4","GPD1L","SPDEF","TGFB3","KIAA0513","ASTN2","RAB5B","SHROOM2","SUOX","CYP46A1","CLU","EFHD1","ASAH1","SIDT1","SLC22A5","ALDH3B2","RHOB","KDM5B","MAGED2","SLC7A8","GADD45G","NCAM2","ETNK2","PTGER3","MCCC2","SUPT4H1","CTPS2","GRIK4","SLC1A2","TCTN1","CERS4","TTC39A","ELOVL2","IGSF3","C11orf80","SLC35E3","ALDH6A1","ADIRF","CPT1A","KIAA0100","ARSD","UNC13B","LCMT1","SNF8","HOXC4","IGFBP2","ZNF652"],"genesDown":["SLC35G2","THEMIS2","MED17","CDKL1","CCDC88A","STAC","IFI16","MICAL2","GSTP1","SNRNP40","GNAI1","HOXA7","PRKCDBP","BATF3","ETV4","YEATS2","SNAI2","RASAL2","USB1","ISG15","GART","AKR1C1","BIRC3","SKI","CSRP2","TGFBI","TRIP10","PTX3","FST","MMP14","COLGALT1","HPSE","C1R","FXYD5","MICALL1","PSAT1","CERK","GLIPR1","CAPN2","SPTBN1","GPX1","NASP","PRSS12","SPRY2","EPHA2","DSE","TOMM22","MIEF1","PTK7","BCL11A","IGFBP7","MAP1B","COL4A1","FOSL1","TAP2","CSNK1E","SPCS3","POLR2F","JOSD1","BTG3","MEIS2","PHC2","CAV1","NRP2","MAP7D1","SERPINB7","LUZP1","MDFIC","TINAGL1","ADAM19","EGFR","CXCL3","HDAC9","CAV2","ADCY7","SERPINB8","SLC7A1","GPR3","STX11","SRSF4","CASP4","PLAUR","NABP1","ACSL5","BIN1","FSCN1","MSN","TNFAIP3","PIK3CD","YBX1","ETS1","AGPAT4","PDGFC","CXCL8","CXCL2","COL4A2","HRH1","GADD45A","SDHAF3","CTSC"]}}'

**Comment by djc183** [comment]
Doesn't work for me, unfortunately.

**Comment by chung88** [comment]
merge both issues:
[https://github.com/schurerlab/LINCSDataPortal_2.0/issues/38](https://github.com/schurerlab/LINCSDataPortal_2.0/issues/38)
[https://github.com/schurerlab/LINCSDataPortal_2.0/issues/43](https://github.com/schurerlab/LINCSDataPortal_2.0/issues/43)
