### ISSUE TITLE
Browse menus from upper-right icons show different search page style

### ISSUE THREAD

**Issue by djc183** [schurerlab/LINCSDataPortal_2.0#44]
Signatures' browsing through the upper-right corner link has a different style of page/navigation buttons versus assays, perturbagens, and model systems.

![image](https://user-images.githubusercontent.com/24969261/64973417-fb948300-d878-11e9-91e7-335f65f5bc67.png)
Assays

![image](https://user-images.githubusercontent.com/24969261/64973447-06e7ae80-d879-11e9-8fb8-aa493c4057ad.png)
Signatures

**Comment by akoleti** [comment]
This is the Pagination issue. I will merge it with the other related issue,
