### ISSUE TITLE
Searching a gene results in perturbagen result

### ISSUE THREAD

**Issue by djc183** [schurerlab/LINCSDataPortal_2.0#50]
Provenance of some data are unclear - on searching for a gene - JQ1, the molecule LSM-6332 is the only result:
![image](https://user-images.githubusercontent.com/24969261/65896057-7af67c00-e37a-11e9-8f4e-3fe70c51cac3.png)

There is no indication on the molecule's landing page regarding how the JQ1 query matched to the page (i.e. no target/MOA/etc. listed).

![image](https://user-images.githubusercontent.com/24969261/65896111-9c576800-e37a-11e9-9d7e-51b18734f728.png)

**Comment by akoleti** [comment]
Not an issue.
