### ISSUE TITLE
Duplicated activity values

### ISSUE THREAD

**Issue by djc183** [schurerlab/LINCSDataPortal_2.0#57]
Activity values for small molecules are duplicated in the activity tables.  Same target name, uniprot accession, endpoint, and value are visible.  Example from Cyproheptadine (LSM-5419):

![image](https://user-images.githubusercontent.com/24969261/66334076-52d0c500-e906-11e9-879b-ffc3bfd98479.png)

**Comment by akoleti** [comment]
![image](https://user-images.githubusercontent.com/12258558/66338739-ba3f4280-e90f-11e9-8717-484d8b619b80.png)

Should be fixed now.
