### ISSUE TITLE
Add synonym into small molecule landing pages

### ISSUE THREAD

**Issue by chung88** [schurerlab/LINCSDataPortal_2.0#59]
https://github.com/schurerlab/LINCSDataPortal_2.0/projects/2#card-27450989
Steps:
(1)  In home http://lincsportal.ccs.miami.edu/beta/home search Chloramphenicol 
(2) click on small molecule name 
(3) opens http://lincsportal.ccs.miami.edu/beta/perturbations/16247  Why the user does not see:  Chloramphenicol
Should we add the Alias (synonym) into the landing page?
[Thanks Afoma]
Yes; I think its a mixture of updating the synonyms so that chloramphenicol and chloromycetin (brand name) are identified as the same thing. And fixing the spelling on "chloromycetny"

**Comment by akoleti** [comment]
fixed.
