### ISSUE TITLE
Incorrect structure/name for LSM-5152

### ISSUE THREAD

**Issue by djc183** [schurerlab/LINCSDataPortal_2.0#70]
Both LDP 1.0 and 2.0 show LSM-5152 to be Ascorbic Acid, but the name does not match the structure shown.

![image](https://user-images.githubusercontent.com/24969261/67133592-84397280-f1db-11e9-9136-9cba3d7c695e.png)
LDP 2.0 entry

![image](https://user-images.githubusercontent.com/24969261/67133603-93202500-f1db-11e9-868f-d1a652542b97.png)
LDP-associated CID page

![image](https://user-images.githubusercontent.com/24969261/67133623-a7fcb880-f1db-11e9-9dd1-7250cde57c63.png)
PubChem entry for Ascorbic Acid

**Comment by chung88** [comment]
The names come from LINCS DB (small molecule registry).

![image](https://user-images.githubusercontent.com/3586358/67133946-49d0d500-f1dd-11e9-9423-31126fa2bced.png)
UniChem (https://www.ebi.ac.uk/unichem/frontpage/results?queryText=LSM-5152&kind=src_compound_id&sources=25&incl=exclude)

**Comment by dusicav** [comment]
SMDB updated. Please propagate the change into LDP1.0 and LDP 2.0.

**Comment by akoleti** [comment]
There there a problem with propagating into LDP1.0.  You can press the index button to do it.

**Comment by dusicav** [comment]
Reindexed, shows correctly in the LDP 1.0.

**Comment by chung88** [comment]
![image](https://user-images.githubusercontent.com/3586358/68498220-5668ac00-0224-11ea-9960-a8d7eeaca14a.png)
